In [111]:
from os import listdir
import pandas as pd
import numpy as np
from IPython.display import display

In [112]:
str_ratings = [f"{letter}{sign}" for letter in ["D", "C", "B", "A"] for sign in ["-", "", "+"]]
values_rating = {str_ratings[i]: 0 + (1/(len(str_ratings)-1))*i for i in range(len(str_ratings))}

In [113]:
def rating2num(str):
    # перобразуем категорию в численную оценку
    return values_rating[str]

print(values_rating)

{'D-': 0.0, 'D': 0.09090909090909091, 'D+': 0.18181818181818182, 'C-': 0.2727272727272727, 'C': 0.36363636363636365, 'C+': 0.4545454545454546, 'B-': 0.5454545454545454, 'B': 0.6363636363636364, 'B+': 0.7272727272727273, 'A-': 0.8181818181818182, 'A': 0.9090909090909092, 'A+': 1.0}

In [145]:
def data_process(df):
    
    # обработка части с оценками esg (обрезать - рейтинг - группировка)
    industry_data_esg = df.loc[df.question_type == "cat", "pillars"::]
    industry_data_esg.iloc[:, 1:] = industry_data_esg.iloc[:, 1:].applymap(rating2num)
    industry_data_esg = industry_data_esg.groupby('pillars').mean().reset_index()

    # обработка части с фин оценками (обрезать - заменить столбец - удалить лишнее)
    industry_data_fin = df.loc[~df.pillars.isin(["E", "S", "G"]) & ~df.questions.isin([np.NAN]), :].copy()
    industry_data_fin["pillars"] = industry_data_fin["questions"]
    industry_data_fin = industry_data_fin.drop(["question_type", "questions", "Unnamed: 0"], axis = 1)

    # соединяем датафреймы 
    res = pd.concat([industry_data_esg, industry_data_fin], ignore_index=True)

    # переворачиваем датасет
    res = res.set_index("pillars").T   

    return res

In [155]:
data_files = listdir("./data")

for industry_file in data_files[:5]:

    industry_data = pd.read_excel(f"data/{industry_file}")
    
    data = data_process(industry_data)

    # print(industry_file, "\n")
    # display(data)

data

pillars,E,G,S,ROE,ROA,EV/EBITDA,EPS,P/E
600376.SS,0.212121,0.333333,0.090909,-4.14159,-0.338674,-,-0.037484,-
600266.SS,0.393939,0.545455,0.340909,0.73474,0.105424,-,-0.064677,69.764216
600675.SS,0.636364,0.393939,0.5,-0.899019,-0.235497,-,0.000551,-
000537.SZ,0.151515,0.30303,0.159091,4.471078,1.924061,-,0.04924,29.643766
001914.SZ,0.030303,0.090909,0.045455,6.907724,1.748386,-,0.23337,11.751482
000002.SZ,0.818182,0.848485,0.704545,9.37478,1.226658,-,0.282768,7.163675
600657.SS,0.575758,0.393939,0.363636,2.25661,0.640151,-,0.027975,21.766562
000402.SZ,0.454545,0.757576,0.568182,-0.789632,-0.191154,-,0.04105,-
GHFC.NS,0.0,0.333333,0.431818,10.537875,7.703958,11.355717,0.149046,33.818915
600383.SS,0.363636,0.424242,0.636364,9.290924,1.344393,-,0.196088,5.427408
000031.SZ,0.424242,0.636364,0.454545,-15.097002,-1.253166,-,-0.097493,-
600606.SS,0.0,0.424242,0.022727,0.489671,0.033138,-,0.010422,84.829721
600743.SS,0.363636,0.393939,0.227273,-71.648533,-7.748452,-,-0.236124,-
000656.SZ,0.393939,0.545455,0.386364,-92.223344,-6.641149,-,-0.58567,-
LSRG.MM,0.727273,0.454545,0.681818,12.5,2.6,4.58,0.73,3.57
600064.SS,0.121212,0.454545,0.136364,14.438657,6.68267,-,0.201249,4.757048
NIRL.BO,0.272727,0.606061,0.159091,35.899327,7.295821,10.119855,0.213166,22.248785
NSEN.NS,0.121212,0.545455,0.318182,8.781191,5.257584,24.047112,0.154643,15.522279
600649.SS,0.242424,0.515152,0.227273,1.755311,0.510529,-,0.044935,26.859504
600639.SS,0.121212,0.363636,0.295455,15.067141,5.968113,-,0.20451,6.688212
600848.SS,0.242424,0.424242,0.454545,5.839304,1.609571,-,0.05798,31.235248
600663.SS,0.363636,0.212121,0.363636,3.877845,0.723515,-,0.038977,45.087236
600823.SS,0.0,0.606061,0.045455,-19.216559,-3.327113,-,-0.175071,-
600895.SS,0.393939,0.484848,0.409091,11.091166,3.075988,-,0.076954,16.627373
600466.SS,0.333333,0.151515,0.5,11.472542,6.752115,-,0.082839,15.275895
000718.SZ,0.0,0.30303,0.068182,3.787219,2.265167,-,0.017104,21.036107
600095.SS,0.0,0.242424,0.159091,-0.90582,-0.317605,-,-0.016568,-
600208.SS,0.121212,0.484848,0.159091,5.008914,1.633195,-,0.031932,9.9634
000540.SZ,0.272727,0.30303,0.136364,-35.136306,-9.102328,-,-0.007354,-

In [172]:
%%python -m venv venv
%./myenv/Scripts/activate
%pip install pandas==1.3.3 numpy==1.21.2 matplotlib==3.4.3 statsmodels==0.12.0
%pip freeze

In [162]:
import statsmodels.api as sm
import matplotlib.pyplot as plt

model = sm.OLS(data['ROE'], data[["E", "S", "G"]])
results = model.fit()

# Вывод результатов
print(results.summary())


# import statsmodels.api as sm
# import numpy as np
# duncan_prestige = sm.datasets.get_rdataset("Duncan", "carData")
# Y = duncan_prestige.data['income']
# X = duncan_prestige.data['education']
# X = sm.add_constant(X)
# model = sm.OLS(Y,X)
# results = model.fit()
# results.params

ImportError: cannot import name 'PD_LT_2' from 'statsmodels.compat.pandas' (c:\Users\pasin\anaconda3\lib\site-packages\statsmodels\compat\pandas.py)

In [156]:
import statsmodels.api as sm
import numpy as np
duncan_prestige = sm.datasets.get_rdataset("Duncan", "carData")
Y = duncan_prestige.data['income']
X = duncan_prestige.data['education']
X = sm.add_constant(X)
model = sm.OLS(Y,X)
results = model.fit()
results.params

ImportError: cannot import name 'PD_LT_2' from 'statsmodels.compat.pandas' (c:\Users\pasin\anaconda3\lib\site-packages\statsmodels\compat\pandas.py)

In [164]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt

# Пример данных
data = {'X1': np.array([1, 2, 3, 4, 5]),
        'X2': np.array([2, 3, 4, 5, 6]),
        'X3': np.array([3, 4, 5, 6, 7]),
        'y': np.array([5, 8, 10, 12, 14])}

df = pd.DataFrame(data)

# Добавляем столбец с константой для коэффициента сдвига
df['const'] = 1

# Создание и обучение модели OLS
model = sm.OLS(df['y'], df[['const', 'X1', 'X2', 'X3']])
results = model.fit()

# Вывод результатов
print(results.summary())

# График регрессии
fig, ax = plt.subplots()
ax.scatter(df['X1'], df['y'], color='red', label='X1')
ax.scatter(df['X2'], df['y'], color='green', label='X2')
ax.scatter(df['X3'], df['y'], color='blue', label='X3')

ax.plot(df['X1'], results.predict(df[['const', 'X1', 'X2', 'X3']]), color='black', linewidth=3, label='Regression Line')
ax.legend()

plt.title('OLS Regression with 3 Independent Variables')
plt.xlabel('X1, X2, X3')
plt.ylabel('y')
plt.show()

ImportError: cannot import name 'PD_LT_2' from 'statsmodels.compat.pandas' (c:\Users\pasin\anaconda3\lib\site-packages\statsmodels\compat\pandas.py)

In [107]:
for industry_file in data_files:
    industry_data = pd.read_excel(f"data/{industry_file}")

In [108]:
industry_data_esg = industry_data.loc[industry_data.question_type == "cat", "pillars"::]
industry_data_esg.iloc[:, 1:] = industry_data_esg.iloc[:, 1:].applymap(rating2num)
industry_data_esg = industry_data_esg.groupby('pillars').mean().reset_index()
industry_data_esg

,pillars,AFLT.MM,601111.SS,ACLL.NS,600012.SS,0694.HK,BLDT.NS,CCRO3.SA,600115.SS,001872.SZ,...,600350.SS,600009.SS,000089.SZ,600548.SS,SCI.NS,SPJT.NS,600717.SS,TCIL.NS,600233.SS,0576.HK
0,E,0.333333,0.606061,0.121212,0.393939,0.454545,0.272727,0.393939,0.393939,0.454545,...,0.212121,0.060606,0.242424,0.727273,0.090909,0.0,0.090909,0.454545,0.242424,0.69697
1,G,0.666667,0.787879,0.363636,0.424242,0.424242,0.666667,0.666667,0.818182,0.515152,...,0.606061,0.393939,0.424242,0.69697,0.151515,0.424242,0.575758,0.818182,0.060606,0.636364
2,S,0.5,0.5,0.295455,0.272727,0.568182,0.409091,0.795455,0.568182,0.295455,...,0.159091,0.181818,0.340909,0.477273,0.386364,0.25,0.295455,0.659091,0.431818,0.363636

In [109]:
industry_data_fin = industry_data.loc[~industry_data.pillars.isin(["E", "S", "G"]) & ~industry_data.questions.isin([np.NAN]), :].copy()
industry_data_fin["pillars"] = industry_data_fin["questions"]
industry_data_fin = industry_data_fin.drop(["question_type", "questions", "Unnamed: 0"], axis = 1)

industry_data_fin

,pillars,AFLT.MM,601111.SS,ACLL.NS,600012.SS,0694.HK,BLDT.NS,CCRO3.SA,600115.SS,001872.SZ,...,600350.SS,600009.SS,000089.SZ,600548.SS,SCI.NS,SPJT.NS,600717.SS,TCIL.NS,600233.SS,0576.HK
396,Return on Equity (TTM),24.9,-74.447954,22.135616,12.393566,-18.822618,36.121957,11.130578,-97.101112,6.907724,...,9.851231,-7.776224,-8.587972,10.798118,11.225568,NaN,4.980592,20.263915,15.491334,18.346225
397,Return on Assets (TTM),-3.1,-10.22919,7.732696,7.203457,-10.095284,12.245282,2.674571,-11.682355,1.748386,...,2.204922,-4.32764,-3.720232,2.908517,6.989491,NaN,2.598783,16.158047,10.547596,2.976638
398,Enterprise Value/EBITDA (TTM),8.06,-16.829068,5.571593,4.19,"-10,66",19.165481,7.486852,"-39,45",6.21,...,NaN,NaN,NaN,NaN,4.399429,-6.83,NaN,12.864728,NaN,NaN
399,Basic EPS (FY),-0.094,-0.407541,0.311719,0.12628,-0.114735,1.899999,0.381186,-0.114447,0.23337,...,0.085738,-0.182941,-0.080766,0.133876,0.22728,-0.27,0.037078,0.49836,0.165272,0.184504
400,Price to Earnings Ratio (TTM),-6.8,8.36,10.056326,11.822006,"-8,51",46.110592,21.295297,"-2,3",11.751482,...,12.166449,NaN,NaN,9.655393,5.263813,NaN,14.369311,17.584517,12.670786,4.198848

In [104]:
data = pd.concat([industry_data_esg, industry_data_fin], ignore_index=True)
data

,pillars,AFLT.MM,601111.SS,ACLL.NS,600012.SS,0694.HK,BLDT.NS,CCRO3.SA,600115.SS,001872.SZ,...,600350.SS,600009.SS,000089.SZ,600548.SS,SCI.NS,SPJT.NS,600717.SS,TCIL.NS,600233.SS,0576.HK
0,E,0.333333,0.606061,0.121212,0.393939,0.454545,0.272727,0.393939,0.393939,0.454545,...,0.212121,0.060606,0.242424,0.727273,0.090909,0.0,0.090909,0.454545,0.242424,0.69697
1,G,0.666667,0.787879,0.363636,0.424242,0.424242,0.666667,0.666667,0.818182,0.515152,...,0.606061,0.393939,0.424242,0.69697,0.151515,0.424242,0.575758,0.818182,0.060606,0.636364
2,S,0.5,0.5,0.295455,0.272727,0.568182,0.409091,0.795455,0.568182,0.295455,...,0.159091,0.181818,0.340909,0.477273,0.386364,0.25,0.295455,0.659091,0.431818,0.363636
3,Return on Equity (TTM),24.9,-74.447954,22.135616,12.393566,-18.822618,36.121957,11.130578,-97.101112,6.907724,...,9.851231,-7.776224,-8.587972,10.798118,11.225568,NaN,4.980592,20.263915,15.491334,18.346225
4,Return on Assets (TTM),-3.1,-10.22919,7.732696,7.203457,-10.095284,12.245282,2.674571,-11.682355,1.748386,...,2.204922,-4.32764,-3.720232,2.908517,6.989491,NaN,2.598783,16.158047,10.547596,2.976638
5,Enterprise Value/EBITDA (TTM),8.06,-16.829068,5.571593,4.19,"-10,66",19.165481,7.486852,"-39,45",6.21,...,NaN,NaN,NaN,NaN,4.399429,-6.83,NaN,12.864728,NaN,NaN
6,Basic EPS (FY),-0.094,-0.407541,0.311719,0.12628,-0.114735,1.899999,0.381186,-0.114447,0.23337,...,0.085738,-0.182941,-0.080766,0.133876,0.22728,-0.27,0.037078,0.49836,0.165272,0.184504
7,Price to Earnings Ratio (TTM),-6.8,8.36,10.056326,11.822006,"-8,51",46.110592,21.295297,"-2,3",11.751482,...,12.166449,NaN,NaN,9.655393,5.263813,NaN,14.369311,17.584517,12.670786,4.198848